apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hwapp
  name: hwapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwapp
  template:
    metadata:
      labels:
        app: hwapp
    spec:
      containers:
        - image: trausch/helloworld
          name: helloworld
